services:
  - type: web
    name: portfolio
    env: node
    buildCommand: |
      npm install
      npm install bcryptjs
    startCommand: |
      node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_PYTHON
        value: /usr/bin/python3
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false 