services:
  - type: web
    name: portfolio
    env: node
    buildCommand: |
      npm install
      npm install bcryptjs
    startCommand: |
      node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_PYTHON
        value: /usr/bin/python3 