services:
  - type: web
    name: portfolio
    env: node
    buildCommand: |
      npm install
      npm install bcryptjs
      # In build.sh or render.yaml
      python -m nltk.downloader punkt -d nltk_data
      # pip install torch numpy nltk && python setup.py
    startCommand: concurrently \"node index.js\" \"uvicorn chat_api:app --host 0.0.0.0 --port 8000\"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_PYTHON
        value: /usr/bin/python3
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false 
