services:
  - type: web
    name: portfolio
    env: node
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules
      npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_PYTHON
        value: /usr/bin/python3 